---
spring.data:
  cassandra:
    contact-points: 10.0.0.2
    keyspace-name: snd_demo
    schema-action: recreate

---

spring:
  profiles: docker
  data:
    cassandra:
      contact-points: 192.168.100.101

---